# Generated by Django 5.2.1 on 2025-05-30 18:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_testimonial_image_path),
        ),
    ]
