# Generated by Django 5.2.1 on 2025-05-30 18:34

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_beforeafterimage_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafterimage',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='beforeafterimage',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_upload_path),
        ),
    ]
